config/routes.rb
Rails.application.routes.draw do
  
  resources :job_profiles
  

  devise_for  :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
                registrations: "registrations" }

  resources :users
  root to: 'job_profiles#index'

end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user

  def self.find_or_create_with_omniauth(auth)
    find_or_create_by(uid: auth['uid'], provider: auth['provider'])
  end
end

app/models/job_profile.rb
class JobProfile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :validatable :recoverable :rememberable
  devise  :database_authenticatable,
          :registerable,
          :trackable,
          :omniauthable,
          omniauth_providers: [:twitter]

  has_one :job_profile
  has_many :identities

  validates_presence_of :email

  def self.create_with_omniauth(auth)
    create do |user|
      user.email = auth['email']
      user.password = Devise.friendly_token[0,20]
      user.name = auth['name']   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
    end
  end


  def self.new_with_session(params, session)
    if session['devise.user_attributes'] and session['devise.identity_attributes'] 
      new(session['devise.user_attributes'], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/job_profiles_controller.rb
class JobProfilesController < ApplicationController
  before_action :set_job_profile, only: [:show, :edit, :update, :destroy]

  # GET /job_profiles
  # GET /job_profiles.json
  def index
    @job_profiles = JobProfile.all
  end

  # GET /job_profiles/1
  # GET /job_profiles/1.json
  def show
  end

  # GET /job_profiles/new
  def new
    @job_profile = JobProfile.new
  end

  # GET /job_profiles/1/edit
  def edit
  end

  # POST /job_profiles
  # POST /job_profiles.json
  def create
    @job_profile = current_user.build_job_profile(job_profile_params)

    respond_to do |format|
      if @job_profile.save
        format.html { redirect_to @job_profile, notice: 'Job profile was successfully created.' }
        format.json { render :show, status: :created, location: @job_profile }
      else
        format.html { render :new }
        format.json { render json: @job_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_profiles/1
  # PATCH/PUT /job_profiles/1.json
  def update
    respond_to do |format|
      if @job_profile.update(job_profile_params)
        format.html { redirect_to @job_profile, notice: 'Job profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_profile }
      else
        format.html { render :edit }
        format.json { render json: @job_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_profiles/1
  # DELETE /job_profiles/1.json
  def destroy
    @job_profile.destroy
    respond_to do |format|
      format.html { redirect_to job_profiles_url, notice: 'Job profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_profile
      @job_profile = JobProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_profile_params
      params.require(:job_profile).permit(:description)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def all
    #byebug
    auth = request.env['omniauth.auth']

    @identity = Identity.find_or_create_with_omniauth(auth)
    
    if user_signed_in?
      if @identity.user == current_user
        redirect_to root_url, notice: "Already linked that account!"
      elsif @identity.user.present?
        raise "error: identity is already used by another user"
      else
        @identity.user = current_user
        @identity.save
        redirect_to root_url, notice: "Successfully linked that account!"
      end
    else
      user = User.create_with_omniauth(auth)
      if user.persisted?
        unless @identity.user.present?
          @identity.user = user
          @identity.save
        end
        sign_in_and_redirect @identity.user, event: :authentication
        if is_navigational_format?
          set_flash_message(:notice, :success, kind: auth['provider'].capitalize)
        end
      else
        session['devise.user_attributes'] = user.attributes
        session['devise.identity_attributes'] = auth.slice('provider', 'uid')
        redirect_to new_user_registration_url, notice: "Please finish registering"
      end
    end
  end

  Devise.omniauth_providers.each do |provider|
    alias_method provider, :all
  end

  def failure
    redirect_to root_url
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    super do
      if resource.persisted?
        auth = session['devise.identity_attributes']
        identity = Identity.find_or_create_by(auth)
        identity.user = resource
        identity.save
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    flash[:notice] = "Hello #{current_user.email}"
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/job_profiles_helper.rb
module JobProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/job_profiles/_form.html.erb
<%= form_for(@job_profile) do |f| %>
  <% if @job_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_profile.errors.count, "error") %> prohibited this job_profile from being saved:</h2>

      <ul>
      <% @job_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/job_profiles/edit.html.erb
<h1>Editing Job Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_profile %> |
<%= link_to 'Back', job_profiles_path %>

app/views/job_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Job Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_profiles.each do |job_profile| %>
      <tr>
        <td><%= job_profile.description %></td>
        <td><%= job_profile.user.email %></td>
        <td><%= link_to 'Show', job_profile %></td>
        <td><%= link_to 'Edit', edit_job_profile_path(job_profile) %></td>
        <td><%= link_to 'Destroy', job_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job profile', new_job_profile_path %>

app/views/job_profiles/new.html.erb
<h1>New Job Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', job_profiles_path %>

app/views/job_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @job_profile.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @job_profile.user %>
</p>

<%= link_to 'Edit', edit_job_profile_path(@job_profile) %> |
<%= link_to 'Back', job_profiles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proinjobs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Created at</th>
      <th>Login at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>
        <td><%= user.current_sign_in_at %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @user.created_at %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>